name = "A New Project"
author = "LingJiuQiSan, YUAXIN"
version = "1.0.1-alpha"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3996c6cf5495a8b086ec6615cd0f55879015dcc463e7e9d726fc904a17833690"

[versions]
forge = "43.3.8"
minecraft = "1.19.2"
