name = "A New Project"
author = "LingJiuQiSan, YUAXIN"
version = "1.0.0-alpha"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "165e84ef0fd1636542dd4cfebf0fcfec3d959280ae376bb0aeaa6b2194191596"

[versions]
forge = "43.3.8"
minecraft = "1.19.2"
