name = "A New Project"
author = "LingJiuQiSan, YUAXIN"
version = "1.0.0-alpha"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "93450e5b1a9b007e168f37e3a0a9fa05863d0ce25ccd92da669eeef5b698ee82"

[versions]
forge = "43.3.8"
minecraft = "1.19.2"
