name = "A New Project"
author = "LingJiuQiSan, YUAXIN"
version = "1.0.0-alpha"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7f590492e8224c895f1076feceb61b7f38bc27a1d4c02f7406c140140286a39f"

[versions]
forge = "43.3.8"
minecraft = "1.19.2"
